package dev.vox.lss.paper;

import org.junit.jupiter.api.Test;

import java.nio.file.Files;
import java.nio.file.Path;

import static org.junit.jupiter.api.Assertions.fail;

/**
 * Fixture regenerator for the {@code nbt-corpus} NATIVE fixtures — hoisted to main by
 * V-1/T1 (version-port-isolation-plan.md) from the 1.21.11 line, where it was invented:
 * rewrites each native fixture as {@code fromV20(v20-corpus twin)} through THIS line's
 * production registry tables, under the standard {@code LSS_REGEN_GOLDENS} discipline
 * (a normal test run returns without touching anything).
 *
 * <p><b>On the 26.2 mainline the natives are FROZEN HISTORY</b> (generated by the object
 * path historically) — this tool exists so a PORT CUT inherits the regeneration lever
 * instead of re-writing it (native bytes are registry-coupled and count-short-shaped
 * per line, so a re-port cannot keep another line's fixtures; the v20 twins are the
 * regeneration source of truth). Two-stage order on a port (runbook): the v20 corpus
 * regenerates FIRST via the serializer test's own {@code LSS_REGEN_GOLDENS} gate, then
 * natives via this tool. Skips {@code duplicate-air.bin} (its deliberate
 * duplicate-palette shape is exactly what fromV20 collapses — converted at a re-port by
 * a hand byte-fold, a named runbook row) and {@code xray-masked.bin} (regenerated by
 * the mask-filter golden test). On MAIN the gate is a byte-identical NO-OP: run it and
 * require {@code git diff} clean (V-1 review — the vanilla-anchored parity tests never
 * read nbt-corpus, the cursor corpus suite catches only CONTENT drift, and the fromV20
 * bijection pins assert against what this tool just wrote, so they FOLLOW a rewrite; a
 * dirty diff here means fromV20's representation drifted and the frozen object-path
 * history would be silently discarded by committing).
 */
class NativeCorpusRegenTool {

    static {
        net.minecraft.SharedConstants.tryDetectVersion();
        net.minecraft.server.Bootstrap.bootStrap();
    }

    @Test
    void regenerateNativeCorpusFromV20() throws Exception {
        if (!"true".equalsIgnoreCase(System.getenv("LSS_REGEN_GOLDENS"))) {
            return;
        }
        Path dir = Path.of("").toAbsolutePath();
        Path module = null;
        for (int depth = 0; depth < 5 && dir != null; depth++, dir = dir.getParent()) {
            if (Files.isDirectory(dir.resolve("src/test/java/dev/vox/lss"))) { module = dir; break; }
            if (Files.isDirectory(dir.resolve("paper/src/test/java/dev/vox/lss"))) { module = dir.resolve("paper"); break; }
        }
        if (module == null) throw new IllegalStateException("cannot locate module tree");
        Path v20Dir = module.resolve("src/test/resources/v20-corpus");
        Path nativeDir = module.resolve("src/test/resources/nbt-corpus");
        var registryAccess = CorpusRegistryAccess.build();
        StringBuilder wrote = new StringBuilder();
        try (var files = Files.list(v20Dir)) {
            for (Path p : files.sorted().toList()) {
                String name = p.getFileName().toString();
                if (!name.endsWith(".bin")) continue;
                if (name.equals("duplicate-air.bin") || name.equals("xray-masked.bin")) continue;
                byte[] nativeBytes = PaperNbtSectionSerializer.fromV20(Files.readAllBytes(p), registryAccess);
                Files.write(nativeDir.resolve(name), nativeBytes);
                wrote.append(name).append(' ');
            }
        }
        fail("native corpus regenerated (" + wrote + "), re-run without LSS_REGEN_GOLDENS and commit the fixtures");
    }
}
