package dev.vox.lss.networking.server;

import org.junit.jupiter.api.Test;
import dev.vox.lss.common.wire.WireSectionCursor;

import java.nio.file.Files;
import java.nio.file.Path;

import static org.junit.jupiter.api.Assertions.fail;

/**
 * Fixture regenerator for the {@code nbt-corpus} NATIVE fixtures — hoisted to main by
 * V-1/T1 (version-port-isolation-plan.md) from the 1.21.11 line, where it was invented:
 * rewrites each native fixture as {@code fromV20(v20-corpus twin)} through THIS line's
 * production registry tables, under the standard {@code LSS_REGEN_GOLDENS} discipline
 * (a normal test run returns without touching anything).
 *
 * <p><b>On the 26.2 mainline the natives are FROZEN HISTORY</b> (generated by the object
 * path historically) — this tool exists so a PORT CUT inherits the regeneration lever
 * instead of re-writing it (native bytes are registry-coupled and count-short-shaped
 * per line, so a re-port cannot keep another line's fixtures; the v20 twins are the
 * regeneration source of truth). Two-stage order on a port (runbook): the v20 corpus
 * regenerates FIRST via the serializer test's own {@code LSS_REGEN_GOLDENS} gate, then
 * natives via this tool. It preserves {@code duplicate-air.bin}'s deliberate duplicate
 * block-palette entries from its v20 twin because fromV20 correctly collapses duplicate
 * resolved ids; {@code xray-masked.bin} is regenerated by the mask-filter golden test.
 * On MAIN the gate is a byte-identical NO-OP: run it and
 * require {@code git diff} clean (V-1 review — the vanilla-anchored parity tests never
 * read nbt-corpus, the cursor corpus suite catches only CONTENT drift, and the fromV20
 * bijection pins assert against what this tool just wrote, so they FOLLOW a rewrite; a
 * dirty diff here means fromV20's representation drifted and the frozen object-path
 * history would be silently discarded by committing).
 */
class NativeCorpusRegenTool {

    static {
        net.minecraft.SharedConstants.tryDetectVersion();
        net.minecraft.server.Bootstrap.bootStrap();
    }

    @Test
    void regenerateNativeCorpusFromV20() throws Exception {
        if (!"true".equalsIgnoreCase(System.getenv("LSS_REGEN_GOLDENS"))) {
            return;
        }
        Path dir = Path.of("").toAbsolutePath();
        Path module = null;
        for (int depth = 0; depth < 5 && dir != null; depth++, dir = dir.getParent()) {
            if (Files.isDirectory(dir.resolve("src/test/java/dev/vox/lss"))) { module = dir; break; }
            if (Files.isDirectory(dir.resolve("fabric/src/test/java/dev/vox/lss"))) { module = dir.resolve("fabric"); break; }
        }
        if (module == null) throw new IllegalStateException("cannot locate module tree");
        Path v20Dir = module.resolve("src/test/resources/v20-corpus");
        Path nativeDir = module.resolve("src/test/resources/nbt-corpus");
        var registryAccess = CorpusRegistryAccess.build();
        StringBuilder wrote = new StringBuilder();
        try (var files = Files.list(v20Dir)) {
            for (Path p : files.sorted().toList()) {
                String name = p.getFileName().toString();
                if (!name.endsWith(".bin")) continue;
                if (name.equals("duplicate-air.bin") || name.equals("xray-masked.bin")) continue;
                byte[] nativeBytes = NbtSectionSerializer.fromV20(Files.readAllBytes(p), registryAccess);
                Files.write(nativeDir.resolve(name), nativeBytes);
                wrote.append(name).append(' ');
            }
        }
        regenerateDuplicateAir(v20Dir.resolve("duplicate-air.bin"), nativeDir.resolve("duplicate-air.bin"));
        wrote.append("duplicate-air.bin ");
        fail("native corpus regenerated (" + wrote + "), re-run without LSS_REGEN_GOLDENS and commit the fixtures");
    }

    /**
     * The identity translator deliberately collapses duplicate resolved palette ids.
     * The duplicate-air fixture pins the opposite vanilla-tolerated shape, so retain its
     * source palette order and packed indexes while resolving dictionary entries through
     * this line's registry. The packed width is unchanged (the fixture's 4-entry block
     * palette remains 4-bit); all other section fields come from the normal translator.
     */
    private static void regenerateDuplicateAir(Path v20Path, Path nativePath) throws Exception {
        byte[] v20 = Files.readAllBytes(v20Path);
        var source = WireSectionCursor.parse(v20, WireSectionCursor.Layout.V20);
        var collapsed = WireSectionCursor.parse(
                NbtSectionSerializer.fromV20(v20, CorpusRegistryAccess.build()),
                WireSectionCursor.Layout.NATIVE);
        if (source.sections().size() != collapsed.sections().size()) {
            throw new IllegalStateException("duplicate-air section count changed during translation");
        }
        var ids = IdentityTables.blockIdsByIdentity();
        var sections = new java.util.ArrayList<WireSectionCursor.WireSection>(source.sections().size());
        for (int i = 0; i < source.sections().size(); i++) {
            var src = source.sections().get(i);
            var dst = collapsed.sections().get(i);
            var srcBlocks = src.blocks();
            if (srcBlocks.isDirect() || srcBlocks.palette().length != 4 || srcBlocks.bits() != 4
                    || dst.blocks().isDirect() || dst.blocks().palette().length != 2
                    || dst.blocks().bits() != srcBlocks.bits()) {
                throw new IllegalStateException("duplicate-air block-palette shape changed: source="
                        + srcBlocks.bits() + '/' + (srcBlocks.isDirect() ? "direct" : srcBlocks.palette().length)
                        + ", translated=" + dst.blocks().bits() + '/'
                        + (dst.blocks().isDirect() ? "direct" : dst.blocks().palette().length));
            }
            int[] palette = new int[srcBlocks.palette().length];
            for (int p = 0; p < palette.length; p++) {
                int dictionaryIndex = srcBlocks.palette()[p];
                String identity = source.dictionary().get(dictionaryIndex);
                Integer id = ids.get(identity);
                if (id == null) {
                    throw new IllegalStateException("unresolved duplicate-air identity " + identity);
                }
                palette[p] = id;
            }
            sections.add(new WireSectionCursor.WireSection(src.sectionY(), dst.nonEmptyBlockCount(),
                    dst.fluidCount(), new WireSectionCursor.WireContainer(srcBlocks.bits(), palette,
                    srcBlocks.data()), dst.biomes(), dst.blockLight(), dst.skyLight()));
        }
        byte[] nativeBytes = WireSectionCursor.emit(
                new WireSectionCursor.WireColumn(java.util.List.of(), sections),
                WireSectionCursor.Layout.NATIVE);
        Files.write(nativePath, nativeBytes);
    }
}
